# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Forkit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya', '~> 12.0'
#  pod 'Material', '~> 3.1.0'

  # Pods for Forkit

end
